version: 2
jobs:
  install_deps:
    docker:
      - image: circleci/node:10.13.0-jessie-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1s-dependencies-{{ checksum "package.json" }}

  build:
    docker:
      - image: circleci/node:10.13.0-jessie-browsers
    steps:
      - run: npm run build
  test:
    docker:
      - image: circleci/node:10.13.0-jessie-browsers
    steps:
      - run: npm run test:ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_deps
      - build:
        requires:
          - install_deps
      - test:
        requires:
          - install_deps
