version: 2.1

commands:
  prepareEnv:
    description: 'install and cache deps'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1s-dependencies-{{ checksum "package.json" }}

jobs:
  build:
    docker:
      - image: circleci/node:10.13.0-jessie-browsers
    steps:
      - prepareEnv
      - run: npm run build
  test:
    docker:
      - image: circleci/node:10.13.0-jessie-browsers
    steps:
      - prepareEnv
      - run: npm run test:ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
