version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0-jessie-browsers
    steps:
      - checkout
      - run: npm i
      - run: npm test
  test:
    docker:
      - image: circleci/node:10.13.0-jessie-browsers
    steps:
      - checkout
      - run: npm i
      - run: npm run build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
